name: cta
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - ctapipe
  - gammapy
  - pip:
      - pytest_runner
      - pytest-ordering
      - https://github.com/cta-sst-1m/protozfitsreader/archive/v1.5.0.tar.gz
