name: nectarchain-dirac
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - ctapipe=0.12
  - numpy=1.22 # higher versions >=1.23 don't work due to astropy4 dependency in ctapipe0.12
  - jupyterlab
  - protozfits=2.0
  - pytest-runner
  - pip
  - dirac-grid  # required by DIRAC
  - fts3  # required by DIRAC
  - voms  # required by DIRAC
  - gfal2  # required by DIRAC
  - pip:
      - CTADIRAC
      - COMDIRAC
