name: cta
channels:
  - default
dependencies:
  - python=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - conda-forge::ctapipe=0.12
  - jupyterlab
  - conda-forge::protozfits=2.0
  - pytest-runner
  - pip
  
