name: nectarchain
channels:
  - default
dependencies:
  - python=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - conda-forge::ctapipe=0.12
  - numpy=1.22.4 # higher versions don't work due to astropy4 dependency in ctapipe0.12
  - jupyterlab
  - conda-forge::protozfits=2.0
  - pytest-runner
  - pip
  
