name: Build and deploy as Apptainer container image to GitHub Container Registry

on:
  push:
  # TODO CHANGE EVENT TRIGGERING TYPE !!!
  #  tags:
  #    - 'v*'
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: write

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Apptainer environment
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and deploy apptainer container image to GitHub Container Registry as ORAS
        # TODO CHANGE REPO HERE !!
        run: |
          apptainer build nectarchain.sif singularity/Singularity
          # echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login --username ${{ github.actor }} --password-stdin oras://${{ env.REGISTRY }} 
          echo "apptainer push nectarchain.sif oras://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          apptainer push nectarchain.sif oras://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # apptainer remote logout oras://${{ env.REGISTRY }}
