name: Build and deploy as Apptainer container image to GitHub Container Registry

on:
  push:
  # TODO CHANGE EVENT TRIGGERING TYPE !!!
  #  tags:
  #    - 'v*'
  pull_request:

jobs:
  deploy-container:
    runs-on: ubuntu-latest

    permissions: read-all|write-all

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Apptainer environment
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.7

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy apptainer container image to GitHub Container Registry as ORAS
        # TODO CHANGE REPO HERE !!
        run: |
          apptainer build nectarchain.sif singularity/Singularity
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login --username ${{ github.actor }} --password-stdin oras://ghcr.io 
          apptainer push nectarchain.sif oras://ghcr.io/jlenain/nectarchain:${{ github.event.release.tag_name }}
          apptainer remote logout oras://ghcr.io
